webapp/models/Album.py
from webapp import Base
from sqlalchemy import CheckConstraint, Column, Integer,String
from sqlalchemy.orm import relationship


class Album(Base):
    """
    A class used to represent an Album

    ...

    Attributes
    ----------
    id : Column
        the id of the album
    name : Column
        the name of the album
    year : Column
        the year of publication of the album
    """

    __tablename__ = "album"

    id  = Column(Integer, primary_key=True, index=True)
    name = Column(String(50), nullable=False)
    year = Column(Integer, CheckConstraint('year > 1900 and year <= 2022'), nullable=False)
    artists = relationship("AlbumArtist", back_populates="album")
    songs = relationship("Song",cascade="all,delete", back_populates="album")

webapp/auth.py
from flask import Blueprint, render_template, request, flash, redirect, url_for, session
from werkzeug.security import generate_password_hash, check_password_hash
from webapp import db_session
from webapp.models.User import User
from webapp.models.Playlist import Playlist
from webapp.models.UserPlaylist import UserPlaylist
from flask_login import login_user, login_required, logout_user, current_user
from sqlalchemy import select, exc

local_session = db_session()

auth = Blueprint('auth', __name__)


@auth.route('/login', methods=['GET', 'POST'])
def login():
    """Function used to login a user. If the credentials inserted by the user are correct then id, name, id_fav_playlist and role are saved in the session

        Returns
        -------
        Return to endpoint /home if users'credentials are correct, otherwise return the template of "login.html"
    """
    if request.method == 'POST':
        email = request.form.get('email')
        password = request.form.get('password')

        stmt = (select(User).where(User.email == email))
        user = None
        try:
            user = local_session.execute(stmt).scalars().first()                
        except exc.SQLAlchemyError as e:
            return str(e.orig)

        if user:
            if check_password_hash(user.password, password):
                login_user(user, remember=True)

                stmt = (
                    select(Playlist.id).
                    join(UserPlaylist, Playlist.id == UserPlaylist.id_playlist).
                    where(UserPlaylist.id_user == user.id).
                    where(Playlist.name == "Preferiti"))

                id_fav_playlist = None
                try:
                    id_fav_playlist= local_session.execute(stmt).scalar()            
                except exc.SQLAlchemyError as e:
                    return str(e.orig)

                session['userid'] = user.id
                session['username'] = user.name
                session['id_fav_playlist'] = id_fav_playlist
                session['role'] = user.role
                
                flash('Login effettuato con successo', category='success')
                return redirect("/home")
            else:                
                flash('Credenziali sbagliate, riprovare.', category='error')
        else:
            flash('Credenziali sbagliate, riprovare.', category='error')

    return render_template("login.html", user=current_user)

@auth.route('/logout')
@login_required
def logout():
    """Function used to logout the authenticated user and set all session's variables to None

        Decorators
        ----------
        @login_required

        Returns
        -------
        Return to auth.login
    """

    session['userid'] = None
    session['username'] = None
    session['id_fav_playlist'] = None
    session['role'] = None
    logout_user()
    return redirect(url_for('auth.login'))

@auth.route('/signUp', methods=['GET', 'POST'])
def signUp():
    """Function used to sign up a user. 
       Sign up is successful only if
       the name or the email entered are not already in the database and
       the password entered and the confirm password are the same and
       the email has to have at least 4 chars and
       the name has to have at least 2 chars and
       the password has to have at least 1 char.

       If any of the above conditions are not respected then a flash message will appear.
       
       If, instead, all the conditions have been met, then the user is signed up and assigned a role.
       In particular, if a user is an artist the role given to him is "ArtistFree", otherwise "UserFree".


        Returns
        -------
        Return the template of "login.html" if the signed up is successful, otherwise return the template of "signUp.html"
    """

    if request.method == 'POST':
        email = request.form.get('email')
        nomeUtente = request.form.get('nomeUtente')
        password = request.form.get('password')
        passwordc = request.form.get('passwordc')
        selectResult = request.form['typeUser']

        if len(email) < 4:
            flash('Email deve essere di almeno 4 caratteri', category='error')
        elif len(nomeUtente) < 2:
            flash('Nome e Cognome deve essere di almeno 2 caratteri', category='error')
        elif len(password)<1:
            flash('Devi inserire una password', category='error')
        elif password != passwordc:
            flash('Le password non corrispondono', category='error')
        else:

            exists_name = local_session.execute(select(User.name).where(User.name == nomeUtente)).scalar()

            exists_email = local_session.execute(select(User.email).where(User.email == email)).scalar()

            if(exists_name is not None):
                flash('Il nome utente esiste già', category='error')
                return render_template("signUp.html")
            if (exists_email is not None):
                flash('L\'email esiste già', category='error')
                return render_template("signUp.html")

            
            newUser = None
            if (selectResult == 'No'):
                newUser = User(
                    name=nomeUtente, 
                    email=email, 
                    password=generate_password_hash(password, method='sha256'),
                    role="UserFree"
                    )
            if (selectResult == 'Si'):
                newUser = User(
                    name=nomeUtente, 
                    email=email, 
                    password=generate_password_hash(password, method='sha256'),
                    role="ArtistFree"
                    )   
        
            playlistPreferiti = Playlist(name='Preferiti') 


            try:
                local_session.add(newUser)
                local_session.add(playlistPreferiti)                
                local_session.commit()
                local_session.flush()
                local_session.refresh(newUser)
                local_session.refresh(playlistPreferiti) 

                user_playlist = UserPlaylist(id_playlist=playlistPreferiti.id, id_user=newUser.id)

                local_session.add(user_playlist)                
                local_session.commit() 

                flash('Account creato!', category='success')
                return redirect(url_for('auth.login'))
            except exc.SQLAlchemyError as e:
                local_session.rollback()
                return str(e.orig)
                
            finally:                                 
                local_session.close()            
    
    return render_template("signUp.html")

        

webapp/views.py
from calendar import month
from flask import Blueprint, render_template, request, flash, redirect, session, url_for
from flask_login import login_required, current_user
from sqlalchemy import select, update, delete, func, exc, desc, or_, and_, extract
from webapp import db_session
from functools import wraps
from webapp.models.User import User
from webapp.models.SongArtist import SongArtist
from webapp.models.Song import Song
from webapp.models.PlaylistSong import PlaylistSong
from webapp.models.Playlist import Playlist
from webapp.models.AlbumArtist import AlbumArtist
from webapp.models.Album import Album
from webapp.models.UserPlaylist import UserPlaylist
from webapp.models.MyFunctions import FunctionSession

local_session = db_session()

views = Blueprint('views', __name__)

def require_role(role_nedeed):
        """Function used to create a new decorator for user roles

        Parameters
        ----------
        role_nedeed : list
                The list of strings of roles nedeed to access in the specific endpoint

        Returns
        -------
        If the current user's role isn't in the list then page_not_found function is returned, otherwise it allows access to the endpoint to the user 
        """

        def wrapper(fn):
            @wraps(fn)
            def decorated_view(*args, **kwargs):

                if (current_user.role not in role_nedeed):
                    return page_not_found()      
                return fn(*args, **kwargs)

            return decorated_view
        return wrapper

@views.route('/', methods=['GET', 'POST'])
def home():
        """Function that redirect the user based on the session

        Returns
        -------
        if the userid is in the session then the user is redirected to the home, otherwise at login

        """
        
        if session.get('userid'):
                return redirect("/home")
        
        return redirect("/login")


@views.route('/home', methods=['GET', 'POST'])
@login_required
def home_authenticated():
        """Function used to load from the database informations about user's playlist and, only if the user is premium, all premium contents

        Returns
        -------
        Return the template "home.html"

        """   
           


        stmt_playlist =(
                select(Playlist.id, Playlist.name).
                join(UserPlaylist, Playlist.id == UserPlaylist.id_playlist).
                where(UserPlaylist.id_user == session['userid']).
                where(Playlist.isPremium == False).
                order_by(Playlist.name))

        playlist_list = None
        try:                     
                playlist_list = local_session.execute(stmt_playlist).all()
        except exc.SQLAlchemyError as e:
                return str(e.orig)

        for playlist in playlist_list:
                if(playlist.id == session['id_fav_playlist']):
                        playlist_list.remove(playlist)

        
        genre_playlists = None
        if(session['role']=="UserPremium" or session['role']=="ArtistPremium" or session['role']=="Admin" ):
         

                genre_playlists_stmt = (select(Playlist.id, Playlist.name).
                        join(UserPlaylist, Playlist.id == UserPlaylist.id_playlist).
                        where(UserPlaylist.id_user == session['userid']).
                        where(Playlist.isPremium == True))

                reccomended_stmt = (
                        select(Song.id, Song.title, Album.name.label('name_album'), Song.length, SongArtist.id_artist, Song.id_album, Song.num_of_plays).
                        join(Album, Album.id == Song.id_album).
                        join(SongArtist, SongArtist.id_song == Song.id).
                        where(extract('month',Song.date_created) == extract('month', func.current_date())).
                        order_by(desc(Song.num_of_plays)).limit(10)
                )              
        
        
                try:
                        genre_playlists = local_session.execute(genre_playlists_stmt).all() 
                        list_songs_reccomended = local_session.execute(reccomended_stmt).all()                      
                except exc.SQLAlchemyError as e:
                        return str(e.orig)

        return render_template("home.html" , genre_playlists=genre_playlists, playlist_list=playlist_list, list_songs_reccomended = list_songs_reccomended)

@views.route('/home/<int:idPlaylist_ToAddSong>/<int:id_song>', methods=['GET', 'POST'])
@login_required
def home_add_song(idPlaylist_ToAddSong,id_song):
        """Function used to add a song into the playlist from home page

        Decorators
        ----------
        @login_required

        Parameters
        ----------
        idPlaylist_ToAddSong : int
            The id of the playlist to which we want to add the song
        id_song : int
            The id of the song

        Returns
        -------
            Return the function home_authenticated()
        """       

        FunctionSession.insert_song_playlist(idPlaylist_ToAddSong, id_song)              

        return home_authenticated()

@views.route('/create-playlist', methods=['GET', 'POST'])
@login_required
def create_playlist():
        """Function used to create a playlist

        Decorators
        ----------
        @login_required

        Returns
        -------
            Return the function home_authenticated()
        """   

        if request.method == 'POST':
                if request.form["create_playlist"]=="create_playlist":
                        nomePlaylist = request.form.get('nomePlaylist')

                        newPlaylist = Playlist(name = nomePlaylist)
                        try:
                                local_session.add(newPlaylist)
                                local_session.commit()
                                local_session.flush()
                                local_session.refresh(newPlaylist)

                                user_playlist = UserPlaylist(id_playlist=newPlaylist.id, id_user=session['userid'])

                                local_session.add(user_playlist)                
                                local_session.commit()

                                flash('Playlist creata con successo', category='success')
                        except exc.SQLAlchemyError as e:
                                local_session.rollback()
                                return str(e.orig)
                        finally:
                                local_session.close()   

        return home_authenticated()

@views.route('/playlists/delete/<int:id>', methods=['GET', 'POST'])
@login_required
def delete_playlist(id):
        """Function to delete a playlist

        Decorators
        ----------
        @login_required

        Parameters
        ----------
        id : int
            The id of the playlist to delete

        Returns
        -------
            Return the function home_authenticated()
        """ 
        if request.method == 'POST':               
                delete_playlist = (
                        delete(Playlist).
                        where(Playlist.id == id))

                try:
                        local_session.execute(delete_playlist)
                        local_session.commit()

                        flash('Playlist eliminata con successo', category='success')
                except exc.SQLAlchemyError as e:
                        local_session.rollback()
                        return str(e.orig)
                finally:                        
                        local_session.close() 

        return home_authenticated()

@views.route('/playlists/<int:id_playlist_selected>', methods=['GET', 'POST'])
@login_required
def get_playlist_selected(id_playlist_selected):
        """Function to load all songs of a playlist and all user's playlist in case he wants to add a song to one of his playlists. 
        Songs are sorted in descending order according to their date of inclusion in the playlist
        It handle also the possibilty of change the playlist's name throught a post request

        Decorators
        ----------
        @login_required

        Parameters
        ----------
        id_playlist_selected : int
            The id of the playlist that the user has selected

        Returns
        -------
            Return the template "playlist-select.html"
        """ 

        if request.method == 'POST':  
                if request.form["change-name-playlist"]=="change-name-playlist":                          
                        nomePlaylist = request.form.get('nomePlaylist')
                        update_playlist = (
                                update(Playlist).
                                where(Playlist.id == id_playlist_selected).
                                values(name=nomePlaylist)
                                )

                        try:
                                local_session.execute(update_playlist)
                                local_session.commit()

                        except exc.SQLAlchemyError as e:
                                local_session.rollback()
                                return str(e.orig)
                        finally:                        
                                local_session.close()


        stmt_song= (
                select(Song.id, Song.title, Song.id_album, Song.length, Album.name.label("name_album"), Album.id.label("id_album"), User.name.label("name_artist"), User.id.label("id_artist")).
                join(PlaylistSong, Song.id == PlaylistSong.id_song).
                join(Album, Song.id_album == Album.id).
                join(SongArtist, Song.id == SongArtist.id_song).
                join(User, User.id == SongArtist.id_artist).
                where(PlaylistSong.id_playlist == id_playlist_selected).
                order_by(PlaylistSong.date_created, Song.id)

webapp/templates/albums.html
{% extends "base.html" %} 

{% block title %}Albums
{% endblock %}

{% block navbar_class_albums %}active{% endblock %}

{% block content %}


<main>
  <h4 class="h4-album" style="color: #fff; margin-bottom: 20px; margin-top: 20px">Album</h4>
  <div class="row row-cols-1 row-cols-md-3 g-4">
    {%- for album in album_list -%}
      <div class="col">
        <a href="{{url_for('views.get_album_selected',id_album_selected=album.id)}}">
          <div class="card h-100" style="position:relative;">
            <img src="/static/album.png">
            <div class="card-body">
              <h3>{{ album.name }}</h3>
              <h5>{{ album.year }}</h5>
                <form action="{{url_for('views.delete_album',id=album.id)}}" method="POST">
                  <button type="submit"  class="btn" name="delete-album">
                    <i class="bi bi-trash-fill" ></i>
                  </button>  
                </form>                 
              </div>
          </div>
        </a>
      </div>
    {%- endfor -%}
  </div>
</main>

{% endblock %}

webapp/templates/artists.html
{% extends "base.html" %} 

{% block title %}Artists
{% endblock %}

{% block content %}


<main>
    <div class="card-container">
      <div class="row">
        {%- for artist in artist_list -%}
          <div class="col">
            <a href="{{url_for('views.get_artist_selected',id_artist_selected=artist.id)}}">
              <div class="card bg-dark">
                  <img class="img-artist" src="/static/artist.png">
                  <div class="card-body">
                    <h3>{{ artist.name }}</h3>
                  </div>
              </div>
            </a>
          </div>
        {%- endfor -%}
      </div>
  </div>
</main>

{% endblock %}

webapp/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    
    <link href="{{ url_for('static', filename='main.css') }}" rel="stylesheet"/>
    <link rel="stylesheet" href="/static/style_sidebar.css" />
    
    

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.3/font/bootstrap-icons.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" />
    

    <link 
    href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" 
    rel="stylesheet" 
    integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" 
    crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
  
    <link rel="icon" type="image/x-icon" href="/static/favicon.ico">
    
    <title>
      {% block title %}
      {% endblock %}
    </title>
  </head>
  <body>

    <div class="main-container d-flex">   
        <div class="sidebar" id="side_nav">
          <div class="header-box px-2 pt-3 pb-4 d-flex justify-content-between">
            <h1 class="fs-4"><span class="bg-white text-dark rounded shadow px-2 me-2">SF</span> <span class="text-white">SpotiFake</span></h1>
            <button class="btn d-md-none d-block close-btn px-1 py-0 text white">
              <i class="fal fa-stream"></i>
            </button>
          </div>
          <ul class="list-unstyled px-2">
            <li class="{% block navbar_class_home %}{% endblock %}"><a href="{{url_for('views.home_authenticated')}}" class="text-decoration-none px-3 py-2 d-block"><i class="bi bi-music-note-list px-2"></i>La tua libreria</a></li>
            <li class="{% block navbar_class_search %}{% endblock %}"><a href="{{url_for('views.search')}}" class="text-decoration-none px-3 py-2 d-block"><i class="bi bi-search px-2"></i>Cerca</a></li>
            <li class="{% block navbar_class_favourite %}{% endblock %}"><a href="{{url_for('views.get_favourite')}}" class="text-decoration-none px-3 py-2 d-block"><i class="bi bi-heart-fill px-2"></i></i>Preferiti</a></li>
            <button type="button" class="link2 px-3 py-2" data-bs-toggle="modal" data-bs-target="#staticBackdrop"><i class="bi bi-plus-circle-fill px-2"></i>Crea playlist</button>
            {%if session['role']=="ArtistFree" or session['role']=="ArtistPremium" or session['role']=="Admin" %}
              <li class="{% block navbar_class_albums %}{% endblock %}"><a href="{{url_for('views.albums')}}" class="text-decoration-none px-3 py-2 d-block"><i class="bi bi-vinyl-fill px-2"></i>Album</a></li>
            {% endif %}      
          </ul>
          <hr class="h-color mx-2">
          <ul class="list-unstyled px-2">
          </ul>
        </div> 
 
      <div class="content">
      
        <nav class="navbar navbar-expand-md navbar-light bg-light mx-auto" id="nav_bar">
          <div class="container-fluid">
            <div class="d-flex justify-content-between d-md-none d-block">
              <button class="btn px-1 py-0 open-btn me-2"><i class="fal fa-stream"></i></button>
              <a class="navbar-brand fs-4" href="#"><span class="bg-dark rounded px-2 py-0 text-white">SF</span></a>
            </div>
            <button class="navbar-toggler p-0 border-0" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <i class="fal fa-bars"></i>
            </button>
            <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
              <ul class="navbar-nav mb-2 mb-lg-0">
                <li class="nav-item">
                  <a class="nav-link active" aria-current="page" href="{{url_for('views.profile')}}">Profilo</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link active" aria-current="page" href="{{url_for('auth.logout')}}">Logout</a>
                </li>
              </ul>
            </div>
          </div>
        </nav>
        <div class="dashboard-content px-3 pt-4">  

          {% with messages = get_flashed_messages(with_categories=true) %} 
            {% if messages %} 
              {% for category, message in messages %} 
                {% if category == 'error' %}
                  <div class="alert alert-danger alter-dismissible fade show" role="alert">
                    {{ message }}
                    <button type="button" id="flash-msg-close-btn" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                  </div>
                {% else %}
                  <div class="alert alert-success alter-dismissible fade show" role="alert">
                    {{ message }}
                    <button type="button" id="flash-msg-close-btn" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                  </div>
                {% endif %} 
              {% endfor %} 
            {% endif %} 
          {% endwith %}  

          {% block content %}
          {% endblock %}
        </div>
      </div>
    </div>

    
    <form action="{{url_for('views.create_playlist')}}" method="POST">
      <div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
          <div class="modal-dialog centered">
          <div class="modal-content">
              <div class="modal-header">
              <h5 class="modal-title" id="staticBackdropLabel" style="color: black;">Crea una nuova playlist</h5>
              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
              </div>
              <div class="modal-body">
                  <label style="color: black;">Inserisci nome playlist </label>
                  <input type="text" id="nomePlaylist" name="nomePlaylist">
              </div>
              <div class="modal-footer">
              <button type="submit" class="btn btn-primary" name="create_playlist" value="create_playlist">Salva</button>
              </div>
          </div>
          </div>
      </div>
    </form>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>

    <script> 

      /**
       * Function that highlights the current page in the sidebar
       */
      $(document).ready(function() {
        $(".sidebar ul li").on('click' , function(){
          $(".sidebar ul li.active").removeClass('active');
          $(this).addClass('active');
        })
      });

      /**
       * Function that opens the sidebar when closed
       */
      $('.open-btn').on('click', function(){
        $('.sidebar').addClass('active');
      })

      /**
       * Function that closes the sidebar when open
       */
      $('.close-btn').on('click', function(){
        $('.sidebar').removeClass('active');
      }) 
    </script>


  </body>
</html> 

webapp/templates/login.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    
    <link href="{{ url_for('static', filename='main.css') }}" rel="stylesheet"/>
    <link rel="stylesheet" href="/static/style_sidebar.css" />
    

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.3/font/bootstrap-icons.css">
    

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" 
      rel="stylesheet" 
      integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" 
      crossorigin="anonymous">
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
  
    <link rel="icon" type="image/x-icon" href="/static/favicon.ico">

    <title>Login</title>

  </head>
  <body>
    
    <div class="center-form">
      {% with messages = get_flashed_messages(with_categories=true) %} 
        {% if messages %} 
          {% for category, message in messages %} 
            {% if category == 'error' %}
              <div class="alert alert-danger alert-dismissible fade show" role="alert">
                {{ message }}
                <button type="button" id="flash-msg-close-btn" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
              </div>
            {% else %}
              <div class="alert alert-success alert-dismissible fade show" role="alert">
                {{ message }}
                <button type="button" id="flash-msg-close-btn" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
              </div>
            {% endif %} 
          {% endfor %} 
        {% endif %} 
      {% endwith %}
    
      <div class="form-container">
         <h1> Accedi ora </h1>
         <form action="" method="POST">
            <div class="data">
              <label>Email</label>
              <input type="email" id="email" name="email" required placeholder="inserisci email">
           </div>
            <div class="data">
               <label>Password</label>
               <input type="password" id="password" name="password" required placeholder="inserisci password">
            </div>
            <div class="btn">
               <button type="submit">Accedi</button>
            </div>
            <div class="login-link">
              <p>Non sei registrato? <a href="signUp">Registrati ora</a></p>
            </div>
         </form>
      </div>
    </div>  


  </body>

webapp/templates/page-not-found.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    
    <link href="{{ url_for('static', filename='main.css') }}" rel="stylesheet"/>
    <link rel="stylesheet" href="/static/style_sidebar.css" />
    

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.3/font/bootstrap-icons.css">
    

    <link 
    href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" 
    rel="stylesheet" 
    integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" 
    crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
  
    <link rel="icon" type="image/x-icon" href="/static/favicon.ico">

    <title>
      Pagina non trovata
    </title>

  </head>
  <body style="background-color: rgba(0,0,0,.75);">
    <div class="form-page-not-found">
      <h1> Pagina non trovata</h1>
      <h5> Non riusciamo a trovare la pagina che cerchi</h5>
      <div class="btn" style="background: black;">
      <a class="btn btn-primary" href="{{url_for('views.home_authenticated')}}" role="button">Torna alla Home</a>
      </div>
    </div>
  </body>